### ISSUE TITLE
Inconsistently with justlog opt out errors

### ISSUE THREAD

**Issue by brian6932** [boring-nick/rustlog#10]
Full gui logs
```php
"https://$INSTANCE/?channel=$CHANNEL&username=$USERNAME"
```
error as expected in rustlog (`User or channel has opted out`).

However, if you navigate to a file for a user who's opted out
```php
"https://$INSTANCE/channel/$CHANNEL/user/$USERNAME"
```
the error is returned as `Not Found`, while justlog returns `User or channel has opted out`

**Comment by boring-nick** [comment]
Fixed in https://github.com/boring-nick/rustlog/commit/607cbfb8b9211e6e4cc998963071b29cdb94a31f
