### ISSUE TITLE
windows permission issue with clickhouse

### ISSUE THREAD

**Issue by tgnom** [boring-nick/rustlog#31]
In contrast to justlog it does not work on windows with docker desktop using wsl for me, due to permission error because of clickhouse.
![rustlogerror](https://github.com/user-attachments/assets/bb13f8f4-97f5-4d68-8bc9-416cd9ecf000)
Fixed by using docker engine on ubuntu distro in wsl instead

**Comment by boring-nick** [comment]
This is some windows docker setup issue, can't help you here. Closing because not related to rustlog
