### ISSUE TITLE
Opt-Out Response Discrepancy 

### ISSUE THREAD

**Issue by RyanPotat** [boring-nick/rustlog#32]
When requesting a user using query parameter, we get a 403
https://logs.flake.sh/list?channel=vmyk&user=seemensteeler

But requesting the same user/channel combination with the below endpoint, we get 404
https://logs.flake.sh/channel/vmyk/user/seemensteeler

This seems to be inconsistent with justlog responses, which returns 403 for both endpoints.
https://logs.potat.app/list?channel=ryanpotat&user=JULIIlAN
https://logs.potat.app/channel/ryanpotat/user/JULIIlAN

Not a major issue, thought I'd mention it though :)

**Comment by boring-nick** [comment]
Will take a look, should be easy to fix

**Comment by boring-nick** [comment]
Fixed in https://github.com/boring-nick/rustlog/commit/f121a1fe01a54e763a8457e65b21443819f6aeba
