### ISSUE TITLE
Occasionally `channelid/*/random?json` can return an empty `messages[]`

### ISSUE THREAD

**Issue by brian6932** [boring-nick/rustlog#5]
It's relatively uncommon, but sometimes in channels with logs, this can happen, not sure what the cause is.
No error or anything.
Instance tested: https://rustlog.zzls.xyz/

**Comment by boring-nick** [comment]
I'm not sure if this is still relevant, but it should be fixed on the latest reworked version, there are checks that messages exist now.

**Comment by brian6932** [comment]
I don't believe this occurs anymore
